# default configuration
baseURL = "https://www.powerplatformportugal.pt"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Power Platform Portugal"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "meetups"
name = "Meetups"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact Us"
weight = 4

[[menu.main]]
URL = "https://www.meetup.com/pt-BR/power_platform_portugal/"
name = "Join Us on Meetup"
weight = 5


# default parameters
[params]
home = "Home"
logo = "images/about/powerplatpt.png"
# theme color
theme_color = "#41228e"
# contact info
phone = "TBD"
email = "powerplatformportugal@gmail.com"
address = "TBD"
# meta description
author = "Ricardo Calejo"
description = "We are Power Platform Portugal"
# google analytics
google_analytics_id = "G-89L8QHPYBN" # Your ID
# copyright
copyright = "Copyright &copy; 2021 Power Platform Portugal"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/f/mwkwyorj" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&region=EG&language=en&callback=initMap"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "fab fa-meetup"
URL = "https://www.meetup.com/pt-BR/power_platform_portugal/"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/company/power-platform-portugal"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/PowerPlatformPortugal"