---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/meetups
  label: Meetups
  create: all
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Configuration
- type: directory
  path: ''
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
